#include <stdio.h>

/*
 * In accordance with the IA32 assembly code in Practice Problem 4.6, we 
 * shoule generate assembly code with "gcc -m32 -S push_test.c".
 *
 * Although the assembly code generated by my push_test.c is slightly 
 * different with that in the question, it literally verify the result of 
 * "pushl %esp".
 *
 * */
int push_test(int result)
{
	int m;
	m = 10;
	
	printf("result = %d\n", result);
	printf("m = %d\n", m);

	asm("movl %%esp, %[val] # Move the stack pointer to a register \n\t"
		"push %%esp  # Push the value in esp to the top of this stack manually. \n\t"
		"popl %[r] \n\t"
		: [val] "=r" (result), [r] "=r" (m)
			
			);

	result = result - m;
	
	return result;
}


int main(int argc, char *argv[])
{

	// The result of testing 'push %esp' is as follows.
	int rst = push_test(12);
	printf("Result = %d\n", rst);
	return 0;
}







